name: Create Tag on Merge

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up npm
        run: |
          # Install npm
          npm install
 
      - name: Set tag
        run: |
          npm version patch
          # Get the branch name from the ref
          TAG_NAME=$(node -p -e "require('./package.json').version")
          
          # Create the tag
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
