name: Create Tag on Merge

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up npm
        run: |
          # Install npm
          sudo apt-get install npm
          npm version patch


      - name: Set tag
        run: |
          # Get the branch name from the ref
          TAG_NAME=$(jq -r .tag_version package.json)
          
          # Create the tag
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
