name: Create Tag on Merge

on:
  push:
    branches:
      - '*'

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up npm
        run: |
          # Install npm
          npm install
 
      - name: Set tag
        id: version-check
        run: |

          master_branch_version=$(git show master:package.json | jq -r .version)
          current_branch_version=$(cat package.json | jq -r .version)
          
          if [ "$master_branch_version" = "$current_branch_version" ]; then
            echo "Package version has not changed. Upgrading..."
            npm version patch
            git push origin HEAD
          else
            echo "Package version has changed. No need to upgrade."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      
      - name: Commit and push updated package.json
        if: steps.version-check.outcome == 'success'
        run: |
          git config --global user.name "whopriyam"
          git config --global user.email "priyambasu16@gmail.com"
          git add package.json
          git commit -m "Auto-upgrade package version"
          git push origin HEAD
        working-directory: ${{ github.workspace }}
