name: Create Tag on Merge

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up jq
        run: |
          # Install jq
          sudo apt-get update
          sudo apt-get install -y jq


      - name: Set tag
        run: |
          # Get the branch name from the ref
          API_KEY=$(jq -r .api_key .github/workflows/config.json)
          
          # Create a tag based on the branch name
          TAG_NAME=$API_KEY
          
          # Create the tag
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
