name: Create Tag on Merge

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up npm
        run: |
          # Install npm
          npm install
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          scope: "@lessonnine"
          always-auth: true
      - name: install ncu
        run: npm install -g npm-check-updates
      - name: update npm dependencies
        run: ncu -u && npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
 
      - name: Set tag
        run: |
          npm version patch
          # Get the branch name from the ref
          TAG_NAME=$(node -p -e "require('./package.json').version")
          
          # Create the tag
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
