name: Create Tag on Merge

on:
  push:
    branches:
      - '*'

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Set up npm
        run: |
          # Install npm
          npm install
 
      - name: Set tag
        id: version-check
        run: |
          git config --global user.name "whopriyam"
          git config --global user.email "priyambasu16@gmail.com"

          master_branch_version=$(git show master:package.json | jq -r .version)
          current_branch_version=$(cat package.json | jq -r .version)
          
          if [ "$master_branch_version" = "$current_branch_version" ]; then
            echo "Package version has not changed. Upgrading..."
            echo master_branch_version
            npm version patch
            git add .
            git commit -m "Auto-upgrade package version"
            git push -f origin $branch
          else
            echo "Package version has changed. No need to upgrade."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        working-directory: .github/workflows
